telegram:
  botUsername: name
  botToken: token
  botPath: ngrok

server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
