telegram:
  botUsername: YouGriffithBot
  botToken: 5820029268:AAFTSgfQZQeXrY5Mp6rbdygyHSU4ZyOkHuI
  botPath: https://3777-45-9-73-12.eu.ngrok.io

server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver